import type { Metadata } from "next";
import { Englebert, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "./provider"; 
import Header from "../components/header";
import GlobalChat from "../components/global-chat";
import { ReactNode } from "react";

const englebert = Englebert({
  variable: "--font-englebert",
  subsets: ["latin"],
  weight: ["400"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="en" className={`${englebert.variable} ${geistMono.variable} antialiased dark`}>
      <body>
        <Provider>
          <div className="flex h-screen overflow-hidden">
            {/* Left Sidebar */}
            <div className="w-16 bg-sidebar border-r border-sidebar-border flex flex-col items-center py-4 space-y-4 shrink-0">
              <div className="w-8 h-8 bg-primary rounded-lg flex items-center justify-center">
                <span className="text-primary-foreground font-bold text-sm">A</span>
              </div>
              <div className="flex flex-col space-y-3">
                <button className="w-10 h-10 rounded-lg bg-sidebar-accent hover:bg-sidebar-accent-foreground/10 flex items-center justify-center transition-colors">
                  <span className="text-sidebar-accent-foreground">🏠</span>
                </button>
                <button className="w-10 h-10 rounded-lg bg-sidebar-accent hover:bg-sidebar-accent-foreground/10 flex items-center justify-center transition-colors">
                  <span className="text-sidebar-accent-foreground">🎮</span>
                </button>
                <button className="w-10 h-10 rounded-lg bg-sidebar-accent hover:bg-sidebar-accent-foreground/10 flex items-center justify-center transition-colors">
                  <span className="text-sidebar-accent-foreground">🏆</span>
                </button>
                <button className="w-10 h-10 rounded-lg bg-sidebar-accent hover:bg-sidebar-accent-foreground/10 flex items-center justify-center transition-colors">
                  <span className="text-sidebar-accent-foreground">⚙️</span>
                </button>
              </div>
            </div>

            {/* Main Content Area */}
            <div className="flex-1 flex flex-col min-h-0">
              <Header />
              <div className="flex-1 flex min-h-0">
                {/* Main Content */}
                <div className="flex-1 overflow-auto">
                  {children}
                </div>
                
                {/* Right Chat Panel */}
                <GlobalChat />
              </div>
            </div>
          </div>
        </Provider>
      </body>
    </html>
  );
}
